---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

LINTER_RULES_PATH: .github/linters

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: (package-lock\.json)

# SEMGREP rulesets
REPOSITORY_SEMGREP_RULESETS:
  - "p/docker-compose"
  - "p/github-actions"
  - "p/owasp-top-ten"
  - "p/react"
  - "p/security-audit"
  - "p/sql-injection"
  - "p/xss"

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
