[package]
name = "youtube_lounge_rs"
version = "0.1.0"
edition = "2021"
authors = ["Anonymous <anon@example.com>"]
description = "A Rust client for the YouTube Lounge API to control YouTube on TV devices"
license = "CC-BY-NC-4.0"
repository = "https://github.com/bertybuttface/youtube-lounge-rs"
documentation = "https://docs.rs/youtube-lounge-rs"
readme = "README.md"
keywords = ["youtube", "api", "client", "tv", "remote"]
categories = ["api-bindings", "multimedia"]
exclude = [
    ".github/",
    "tests/",
    "examples/",
    "youtube_auth.json"
]

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
urlencoding = "2.1"
bytes = "1.0"
once_cell = "1.20"

[dev-dependencies]
tokio-test = "0.4"
serde = { version = "1.0", features = ["derive"] }
mockall = "0.11"
