---
# This workflow audits the dependencies of a Rust project using cargo-audit.
name: "Audit Dependencies"
permissions: read-all
on:
  pull_request:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

  # Rerun periodically to pick up new advisories
  schedule:
    - cron: "0 0 * * *"
  # Run manually
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
        # with:
        #   # Comma separated list of issues to ignore
        #   ignore: RUSTSEC-xxxx-nnnn
