---
# This workflow orchestrates the release process by waiting for other checks to pass
name: Release Orchestrator
permissions: read-all

on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

jobs:
  check-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: "MegaLinter"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait for audit check
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: "Audit Rust Dependencies"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Trigger release workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"branch": "${{ github.ref_name }}"}'
