---
name: Release
permissions: read-all

# This workflow is triggered manually
on:
  workflow_dispatch:

jobs:
  release:
    uses: semantic-release-action/rust/.github/workflows/release-library.yml@v5
    with:
      toolchain: stable
      # Optional: GitHub App authentication for pushing to protected branches
      # github_app_id: ${{ vars.SEMANTIC_RELEASE_GITHUB_APP_ID }}
    secrets:
      cargo-registry-token: ${{ secrets.CRATES_IO_TOKEN }}
      # Optional, but must be specified with github_app_id input is set
      # github_app_private_key: ${{ secrets.SEMANTIC_RELEASE_GITHUB_PRIVATE_KEY }}
    permissions: write-all
